version: 2
before:
  hooks:
    - go mod tidy

builds:
  # Only allow Darwin releases for now...
  - id: viscue
    main: .
    binary: viscue
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'

brews:
  - repository:
      owner: rmscoal
      name: homebrew-tap
    commit_author:
      name: rmscoal
      email: rmscoaldev@gmail.com
    name: viscue
    homepage: "https://github.com/rmscoal/viscue"
    description: "Your terminal password manager"